---
- ansible.builtin.include_tasks: install.yml
  tags: install
  when: ansible_os_family not in ['RedHat', 'Rocky']

- ansible.builtin.include_tasks: install-centos.yml
  tags: install
  when: ansible_os_family in ['RedHat', 'Rocky']

- ansible.builtin.include_tasks: configure.yml
  tags: configure
  when: ansible_os_family not in ['RedHat', 'Rocky']

- ansible.builtin.include_tasks: configure-centos.yml
  tags: configure
  when: ansible_os_family in ['RedHat', 'Rocky']

- ansible.builtin.include_tasks: secure.yml
  tags: secure

- ansible.builtin.include_tasks: databases.yml
  tags: databases

- ansible.builtin.include_tasks: users.yml
  tags: users
